recipe: default.v1
language: es
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 5
- name: DIETClassifier
  epochs: 60
  random_seed: 42
  model_confidence: softmax
  ranking_length: 10
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 60
  random_seed: 42
  model_confidence: softmax
  ranking_length: 5
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 60
- name: TEDPolicy
  max_history: 5
  epochs: 60
  random_seed: 42
  constrain_similarities: true
assistant_id: 20260107-102407-prompt-caliper
